### ISSUE TITLE
Reduce specificity of default styles

### ISSUE THREAD

**Issue by WickyNilliams** [reactjs/react-tabs#101]
The BEM classes added to each component are super useful for applying custom styling. However, because the default styles have a high specificity (e.g. `.react-tabs [role=tab][aria-selected=true]:hover`), the purpose of adopting BEM is defeated slightly.

I propose using low specificity BEM classes for the default styles, so that they may be overridden more easily

**Comment by HonzaMikula** [comment]
The best would be possible turn off style entirely.

**Comment by darkyen** [comment]
Just a suggestion: Let us pass our own style?

**Comment by rhys-vdw** [comment]
> Just a suggestion: Let us pass our own style?

I don't like this option because it still forces the project to depend on `js-stylesheet`.

> The best would be possible turn off style entirely.

This is currently possible @HonzaMikula, as a global [here](https://github.com/reactjs/react-tabs/blob/213e243e44478f26e8ea3b138d2132a4993b615a/src/components/Tabs.js#L36-L40).

Yes. It would be better if `js-stylesheet` were not a dependency, and the styles could optionally be imported like so:

```jsx
import jss from 'js-stylesheet';
import { Tabs, /* blah */ } from 'react-tabs';
import TabStyles from 'react-tabs/styles';

function MyTabs() {
  jss(TabStyles);
  return (
    <Tabs>
       // blah blah
    </Tabs>
  )
}
```

Right now this project adds `js-styles` as a dependency, even though my project doesn't use your styles option!

An alternate implementation would move `js-stylesheet` to `optionalDependencies`, and instead of `import`ing it at the top of [`Tabs.js`](https://github.com/reactjs/react-tabs/blob/213e243e44478f26e8ea3b138d2132a4993b615a/src/components/Tabs.js#L4), it could be moved into [here](https://github.com/reactjs/react-tabs/blob/master/src/components/Tabs.js#L62) like so:

```js
  componentDidMount() {
    if (useDefaultStyles) {
      // Will fail if *optional* dependency is not included - this responsibility is on the client.
      require('js-stylesheet')(require('../helpers/styles.js')); // eslint-disable-line global-require
    }
  },
```

But this approach is less optimal because the `/helpers/styles.js` file will still be bundled by webpack (which detects and replaces `require` statements).

**Comment by lautarodragan** [comment]
It'd be awesome if we could pass a prop `useDefaultTyles={false}`to disable default styles instead of calling `Tabs.setUseDefaultStyles(false)` globally. It feels more intuitive.

I think that for this to be possible the default styles would need to be included as inline styles (`style={props.useDefaultStyles && defaultStyles`), otherwise one Tabs element set to use default styles would pollute the entire CSS and impact all other Tabs elements in the web app.

I think you could also drop the dependency on `jss` this way, or at least pave the way.

**Comment by lautarodragan** [comment]
@danez how did you resolve this in the end? I'm searching for `useDefaultStyles` on the diff in of #161 and can only find it in the old part of the diff, not the new. Also I see you deleted `helpers/styles.js` entirely.

**Comment by danez** [comment]
The idea is to not force anyone to use a specific css methodology. So instead of having style injected by default with `js-stylesheets`, react-tabs does not do anything by default regarding to css (besides adding classnames to the rendered elements). It is up to the user to wire things up. There is a new file `style/react-tabs.css` which can be for example imported when using webpack css-loader

```js
import 'react-tabs/style/react-tabs.css';
```

Or it can be simply copied.
I can maybe also add a sass/less variant that can be imported in someones own sass/less files.

It is a little bit more work to initially get the default style going, but a lot of people wanted to disable the default style (with `js-stylesheet`) anyway.

Does that sound reasonable? What do you think?

**Comment by WickyNilliams** [comment]
Sounds like the right solution to me 👍

**Comment by lautarodragan** [comment]
Yep, sounds perfect to me!
