### ISSUE TITLE
Flag to use display:none instead of mount/unmount

### ISSUE THREAD

**Issue by Pongetti** [reactjs/react-tabs#126]
Hello,

React-Tabs works by mounting/unmounting the active/inactive tabs and this is exactly how it should behave.  Unfortunately, I've ran into a situation where I absolutely need an inactive tab to be in the DOM.  It seems like it would be reasonably simple to add a flag on the Tabs component that would decide between using the mount/unmount method vs using the good ol' style=display:none method.

Any chance we could add that in?

The situation causing the issue is that I have a bunch of clients who had a particular form customized in the old system.  To avoid breaking all their forms without doing any real work, I'm just going to stick the old form in the DOM and serialize what's in the DOM when they hit submit button.  This form is in a tab though, so it doesn't work when the tab is inactive.

Thanks!

**Comment by danez** [comment]
You can do that by setting `forceRenderTabPanel` to true

**Comment by Pongetti** [comment]
Ah yes!  I swear I had looked at the PropTypes in the source and found nothing of interest but problem solved, thanks!  :+1:

**Comment by stebogit** [comment]
Hey @danez I have the same issue @Pongetti had, however using `forceRenderTabPanel` doesn't really solve my problem, because I can not allow all my `Tabs` to be mounted and rendered at the same time (too much data would be loaded).
Is there a way to avoid the unmounting of the `Tabs` when not displayed and not having them all mounted together?

`React-Bootstrap` components would allow to do this somehow, but I noticed those `Tabs` would render so many times before reaching a stable output, which I believe will cause some performance issues.

Thanks

**Comment by joepvl** [comment]
Hi @stebogit, it's not entirely clear to me what you are after here. The more granular version of `forceRenderTabPanel` is the `forceRender` prop on individual `<TabPanel>`s, maybe you could use that?

What I'm reading from your comment is that you'd like to keep content rendered after it's been loaded the first time (which you do on mount), but at the same time you want to avoid loading all of the data your individual tabs depend on at once. There are probably multiple ways of solving the underlying problem independently of react-tabs, but I do think it might work if you only set `forceRender` to `true` on a `<TabPanel/>` once its content has loaded. How exactly you do this will depend on the way your code is structured, but you'll need to keep some state in the component that renders your `<Tabs/>` so it knows which panels to apply `forceRender` to.

**Comment by stebogit** [comment]
Thanks @joepvl for the hint, I'll give it a try.

I'm just wondering if my case is uncommon. 🤔 
My `<TabPanel>`s contain components that show data which they fetch one time only on mount. Since the amount of data is potentially a lot, but not all `<Tabs>` are necessarily viewed by the user, not mounting all the components (thus fetching all the data) at once is beneficial for mobile users for example. Once the data is loaded on the page and the components rendered we don't want to unmount them to avoid unnecessary data fetching at their next mount, here to improve performances and the user experience.

In my case there is a fair amount of data involved so this becomes more relevant, but in general what's the benefit of unmounting components when "hidden" or render them all at first load? Isn't "lazy rendering" always a good thing?
I expected that would have been the default behaviour.

**Comment by joepvl** [comment]
@khanhlu2013 In that case, why not set `forceRenderTabPanel={true}` and set `display: none` using css on any tab that doesn't have your `activeTabPanelClassName`? That's how the prop is meant to be used.

You don't explicitly need to set it to `false`, that's its default value.

**Comment by khanhlu2013** [comment]
@joepvl, i didn't explain myself well. Let me put it differently. I propose making a flag: `cacheRenderedTab`. When `forceRenderTabPanel` is `true`, `cacheRenderedTab` is ignored. Otherwise, if `forceRenderTabPanel` is `false` and `cacheRenderedTab` is `true` , then when we switch tab, it will NOT be un-mount from the dom ( it is simply hided with css ) . That way, when we switch back to that tab, there is no need for creating and mounting it again (simply change css to display it) . `cacheRenderedTab` should be `true` by default to achieve the most lazy/performance effect.

**Comment by joepvl** [comment]
So you would also like to start out with just the initially rendered tab in the DOM, but keep it in the DOM as you switch away from it? As I mentioned back in April, I think you can do this by setting `forceRender` on a `<TabPanel/>` after its initial render (I don't have time to try it myself but I'd much appreciate it if you reported back if you decide to find out). However, I'd like to stress that I don't think this would be an idiomatic way of doing things in React — it's an imperative solution to a problem that's better solved declaratively.

I'll try to clarify: the "underlying problem" I was alluding to in my earlier comment (directed at @stebogit) was that in cases like this you're generally better off fetching your data further up the tree, or abstracting fetching out of your component logic completely, so you have more control over caching and you're not dependent on the component's own lifecycle for managing the data you need it to render. Separating these concerns (data fetching and rendering) will in most cases end up simplifying your code, while giving you more power and control over your data and rendering.

**Comment by luisgjb** [comment]
> Thanks @joepvl for the hint, I'll give it a try.
> 
> I'm just wondering if my case is uncommon. 
> My `<TabPanel>`s contain components that show data which they fetch one time only on mount. Since the amount of data is potentially a lot, but not all `<Tabs>` are necessarily viewed by the user, not mounting all the components (thus fetching all the data) at once is beneficial for mobile users for example. Once the data is loaded on the page and the components rendered we don't want to unmount them to avoid unnecessary data fetching at their next mount, here to improve performances and the user experience.
> 
> In my case there is a fair amount of data involved so this becomes more relevant, but in general what's the benefit of unmounting components when "hidden" or render them all at first load? Isn't "lazy rendering" always a good thing?
> I expected that would have been the default behaviour.

+1
Exactly same here, and now i think if am i wrong?

**Comment by jvsonica** [comment]
I had the same use case where I wanted to keep the loaded tabs rendered after changing tab (mainly due to the amount of data that was being fetched in the initial tab).
To solve it, I added `loadedTabs` field to my state (array of positional indices) which I initialized with the initial tab and updated with `<Tabs>`'s `onSelect`.

Then, following @joepvl advice, each `<TabsPanel>` looks up if its index is in `loadedTabs`, and populates `forceRender` accordingly: once it is loaded once, the content will be kept in DOM and are simply hidden when the tab is inactive, preventing unmounting when you change tabs.

I was able to reproduce this [here](https://codesandbox.io/s/4jjy6qq3m4), comment out the styling import to check that both tab's content are in DOM.

**Comment by joepvl** [comment]
@jvsonica That's exactly what I had in mind, thanks for reporting back!

**Comment by joepvl** [comment]
I just realized that, as far as I can tell, this could be solved by wrapping `TabPanel` with some custom logic to make it set `forceRender` on the panel after the first time it's selected:

```jsx
class LazyTabPanel extends React.Component {
  state = { initialized: false };

  componentDidUpdate() {
    if (this.props.selected && !this.state.loaded) {
      this.setState({ initialized: true });
    }
  }

  render() {
    return <TabPanel forceRender={this.state.initialized} {...this.props} />;
  }
}
LazyTabPanel.tabsRole = "TabPanel";
```

Use it instead of `TabPanel` for any tabs that need to remain in the DOM after they're first selected. If you want to style it differently before and after it's been loaded, you could add a callback prop, e.g. `onLoad` (which is more like `onFirstSelect`), so you can respond to that in the parent component.

Note that a variable named `loaded` wouldn't be entirely accurate here. Just because it was selected, we can't conclude that it has completed loading as well. That's why I went with `initialized` — perhaps `wasSelected`, `selectedAtLeastOnce`, or something similar would be even more accurate. The principle remains the same though.

---
Bonus: Hooks version!

```jsx
const HookedLazyTabPanel = props => {
  const [initialized, setInitialized] = useState(false);
  useEffect(
    () => {
      if (props.selected && !initialized) {
        setLoaded(true);
      }
    },
    [props.selected || initialized]
  );

  return <TabPanel forceRender={loaded} {...props} />;
};
HookedLazyTabPanel.tabsRole = "TabPanel";
```

(In this version, the effect callback only gets called once, since what we passed as the item in the dependency array for `useEffect` will always be `true` after the first time `props.selected` was `true`! This is some overoptimization on my part, but I was just having fun here. 😉)

**Comment by jvsonica** [comment]
The heads up regarding the naming makes sense. In that sense, I also believe you meant `this.state.initialized` in `componentDidUpdate()`.

This solution seems way neater, thanks a lot for the examples and the tips!

**Comment by joepvl** [comment]
True, I missed that one — thanks! Edited the comment so copy/pastes aren't broken.

**Comment by marcvangend** [comment]
Thanks @joepvl. I'm a bit late to the party but the lazy tab panel works great. That said I did notice a small mistake in the hooked version: where it says "loaded" you meant "initialized". I also changed the useEffect dependencies a little because it triggered the react-hooks/exhaustive-deps eslint rule. Here's my resulting code, hope it helps anyone:

```jsx
const LazyTabPanel = props => {
  const [initialized, setInitialized] = useState(false);
  useEffect(() => {
    if (props.selected && !initialized) {
      setInitialized(true);
    }
  }, [props.selected || initialized]);

  return <TabPanel forceRender={initialized} {...props} />;
};
LazyTabPanel.tabsRole = 'TabPanel';
```
