### ISSUE TITLE
Allow overriding CSS classes for TabPanel

### ISSUE THREAD

**Issue by ekohl** [reactjs/react-tabs#131]
This comes from https://github.com/reactjs/react-tabs/issues/127#issuecomment-245894498.

Currently it's possible to override CSS classes for TabList, but this isn't possible for TabPanel. Adding this support would improve the customizability.

**Comment by danez** [comment]
You can use the `classname` prop on TabPanels to change the classnames.
Active/Inactive classname doesn't make sense I think as usually only the active TabPanel is shown anyway. OR can you explain what exactly you are missing?

**Comment by ekohl** [comment]
I later realized that too. On the other hand, it does apply the ```ReactTabs__TabPanel--selected``` class and you may want to change that too.

**Comment by joepvl** [comment]
I realize it's kind of pedantic, but to be consistent it makes sense to me that the `ReactTabs__TabPanel--selected` class should either be customizable with an `activeTabPanelClassName` prop like the one for `<Tab>` (like @ekohl is suggesting), or if it's not there for a good reason then we may be better off removing it entirely for clarity's sake.

Another option would be to let users choose, when setting `forceRenderTabPanel={true}`, whether to use `display: none` to hide inactive/unselected tabs (sensible default), **OR** add a provided (with fallback to the current default) class to the selected `<TabPanel>`, **OR** mix a provided `activeTabPanelStyle` prop into the `style` prop for that `<TabPanel>`. I would, however, be reluctant to add stuff like this because of the increased API surface and the component simply trying to do too much, which feels wrong to me. I wonder if there is a more general idiomatic way of modifying what are essentially display-related properties (or "display logic", as opposed to "business logic" which should IMO always be completely encapsulated) of a component that we could apply here without basically rewriting the whole package. Would appreciate any thoughts on this, though I realize this probably isn't the best place for such a discussion.

As a side note, I think it's strange that the prop is called __*active*TabClassName__, but the default class uses the word __*selected*__ to indicate its state. Which is it, *active* or *selected*? Or do they actually mean different things?

**Comment by ekohl** [comment]
> I realize it's kind of pedantic, but to be consistent it makes sense to me that the ReactTabs__TabPanel--selected class should either be customizable with an activeTabPanelClassName prop like the one for <Tab> (like @ekohl is suggesting), or if it's not there for a good reason then we may be better off removing it entirely for clarity's sake.

That's a much better description of my point.

> Another option would be to let users choose, when setting forceRenderTabPanel={true}, whether to use display: none to hide inactive/unselected tabs (sensible default), OR add a provided (with fallback to the current default) class to the selected <TabPanel>, OR mix a provided activeTabPanelStyle prop into the style prop for that <TabPanel>. I would, however, be reluctant to add stuff like this because of the increased API surface and the component simply trying to do too much, which feels wrong to me. I wonder if there is a more general idiomatic way of modifying what are essentially display-related properties (or "display logic", as opposed to "business logic" which should IMO always be completely encapsulated) of a component that we could apply here without basically rewriting the whole package. Would appreciate any thoughts on this, though I realize this probably isn't the best place for such a discussion.

I agree that it would add a lot of complexity for very little value.

> As a side note, I think it's strange that the prop is called activeTabClassName, but the default class uses the word selected to indicate its state. Which is it, active or selected? Or do they actually mean different things?

A very valid point.

**Comment by joepvl** [comment]
Ah, reading #136 made it clear to me why that class is there in the first place. It's to enable the use of animations in combination with `forceRenderTabPanel`. Yep, I think that convinced me that adding an `activeTabPanelClassName` prop on `<Tabs>` is a good idea.

**Comment by alexanderwallin** [comment]
One alternative to providing customization props for everything is to provide composer functions that you can use to easily wrap your custom components inside higher-order tab components.

Roughly, something like:

```js
// MyTabPanel.js
import { asTabPanel } from 'react-tabs'
import classNames from 'classnames'

const MyTabPanel = ({ isSelected, children }) => (
  <div className={classNames('MyTabPanel', { 'is--selected': isSelected })}>
    {children}
  </div>
)

export default asTabPanel(MyTabPanel)
```

**Comment by danez** [comment]
Overwriting the class names is now the default behaviour in 1.0.0

**Comment by joepvl** [comment]
I noticed that! And I see the `active`/`selected` issue is now cleared up as well :).
