### ISSUE TITLE
Tab Panel animation

### ISSUE THREAD

**Issue by timhecker** [reactjs/react-tabs#136]
Hi, 
I'm using react-tabs disabling the default styling and with my custom classes. I'd like to animate the tab panel entering with a fade-in or something like that, but nothing happens. 
Here my sass rules: 
`.l-tabs__panel {`
` opacity: 0;`
  `transform: translateY(20%);`
 ` transition: opacity $transition-timing $transition-easing, transform $transition-timing $transition-easing;`
`  &[class*='--selected'] {`
    `opacity: 1;`
    `transform: translateY(0);`
  `  }`
`}`

I tried also with ReactCSSTransitionGroup in this way: 
`<TabPanel>`
        `<ReactCSSTransitionGroup`
         ` transitionName="fade-in"`
          `transitionEnterTimeout={250}`
         ` transitionLeaveTimeout={250}`
      `  >`
          `{myContent}`
        `</ReactCSSTransitionGroup>`
     ` </TabPanel>`

but nothing happens, when I select between my tabs. Please is there someone who could help me?

Thanks

**Comment by joepvl** [comment]
Have you tried setting the `forceRenderTabPanel` boolean prop on `<Tabs>` (like `<Tabs forceRenderTabPanel>`)? This will change `<Tabs>`' behaviour from not rendering inactive panes at all to rendering them but not displaying them (using `display: none`). I'm pretty sure this would fix your issue.

Thanks for filing this BTW, we were actually wondering whether that `ReactTabs__TabPanel--selected` class on `<TabPanel>` was there for a good reason in #131. Now we know why it's there, and we may well allow you to change the name of that class as well in the future, so you won't have to use that delightful `&[class*='--selected']` selector anymore 😉 .

**Comment by timhecker** [comment]
Thanks @joepvl for the answer, but using `forceRenderTabPanel` prop on `<Tabs>` I can't see any differences: I always see inline style `display: none` on hidden tab panel, in both cases (`<Tabs forceRenderTabPanel>` or `<Tabs forceRenderTabPanel={false}>`). Is there a way to control inline styles?

**Comment by joepvl** [comment]
Well now, seems there were a few misconceptions on my side here. Firstly, I hadn't realized css transitions don't work at all when using `display: none` on a transition target. Secondly, `react-tabs` *does* render the `<TabPanel>`s if you don't supply `forceRenderTabPanel` (it defaults to `false`), it just doesn't render its `children` (see [TabPanel.js#L50](https://github.com/reactjs/react-tabs/blob/de7c5e6/src/components/TabPanel.js#L50)).

You can use `@keyframe` animation instead, though. I made a jsbin to test/demonstrate this: [jsbin.com/weyaqi](https://jsbin.com/weyaqi). Got a bit carried away styling stuff there, but I'm sure you get the idea 😅.

**Comment by timhecker** [comment]
Thanks, perfect, very nice.

**Comment by joepvl** [comment]
Great! And again, thanks for filing this, it's helped me see that more comprehensive documentation around the options the component takes and their caveats would be a valuable addition.

**Comment by davidsamacoits** [comment]
Hey! This issue has been closed since you solved your problem but I'd like to go further with animations. Fading in is working just fine, but what if I also want to fade out the content before switching tabs? I was thinking of using _react-transition-group_ but it doesn't to work properly... Any ideas or suggestions?

**Comment by Alfrex92** [comment]
Thank you @joepvl for the jsbin. I was helpful for me too. I just have a question, why are you using Tabs.setUseDefaultStyles(false); ?

**Comment by joepvl** [comment]
@Alfrex92 you're welcome! At the time I wrote that comment and the example, `Tabs.setUseDefaultStyles` was used to disable the default styling. I'm guessing I needed to do this in order to be able to illustrate my point. This API was removed in 1.0 along with the js-based default styles, so that line isn't relevant anymore unless you're using an unsupported version of the package.

In fact, if you'd need to change a few things if you wanted to update the bin to work with the current react-tabs@2.2.1:
* remove `Tabs.setUseDefaultStyles` call
* change  the `activeTabClassName` prop to `selectedTabClassName` and move it to `<Tabs>`
* change the style for the `<TabPanel>` (the `.l-tabs__panel` block) to have `display: none` for the default state, and `display: flex` for the selected state
* you could also add `selectedTabPanelClassName='l-tabs__panel--selected'` to `<Tabs>` and switch out the odd `&[class*='--selected']` selector for `&--selected`

**Comment by Alfrex92** [comment]
@joepvl  thank you so much for the update.
I create a codesandbox with the updated code.
https://codesandbox.io/s/9lv5o45wv4
may you confirm if everything is correct?

**Comment by joepvl** [comment]
@Alfrex92 awesome, thanks for that! Looks good to me, except for one thing: the `className` for the `<TabList>` doesn't match the css (it has "[...]tab-list**s**" instead of "[...]tab-list" — extra "s" at the end). That's why the tabs are floating above the panel. Other than that, 👍!

**Comment by Alfrex92** [comment]
@joepvl thank you for the feedback. I updated the codesandbox.

**Comment by DavidTheSimon** [comment]
I don't see why everyone makes this so complicated. No offence!
The easy way is to use a little css snippet.

`.tab-pane.active {
    animation-name: fadeIn;
    animation-duration: 300ms;
    animation-timing-function: linear;
  }`

`@keyframes fadeIn {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}`

**Comment by rajendrabadri123** [comment]
.tab-pane.active { animation-name: fadeIn; animation-duration: 300ms; animation-timing-function: linear; }

@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }


This really cool, working code :+1:  loved it

**Comment by jonathanpalma** [comment]
Thanks @DavidTheSimon, it works perfectly :tada: 

I would like to add a little tip to save some time to those who are trying to implement this feature. In order to overwrite the default selected tab panel class name, you can use `selectedTabPanelClassName` prop in your `Tabs` component, for more information you can refer to the [documentation](https://github.com/reactjs/react-tabs#selectedtabpanelclassname-string). 

In the following example I will use `MyTab__panel--selected` but you can use any string that makes sense for your project

MyComponent.js
```tsx
<Tabs selectedTabPanelClassName="MyTab__panel--selected">
  {/* ... */}
</Tabs>
```

MyComponent.css
```css
@keyframes fadeIn {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  } 
}

.MyTab__panel--selected {
  animation-name: fadeIn;
  animation-duration: 250ms;
  animation-timing-function: linear;
}
```
