### ISSUE TITLE
Force update

### ISSUE THREAD

**Issue by upq** [reactjs/react-tabs#147]
Hello,
Im using **other components inside a ```TabPanel ```,** those componenets are connected to a **redux store** and they update nicely when there is an update in the store , however **if used inside a tabpanel they don't update**, what is the work around for that is there **an update method** or a way to force a the ```Tabs ```or the ```TabPanel ```to update to reflect the changes?
Thanks.

**Comment by joepvl** [comment]
Hi! I'm using Redux in the same way and am experiencing no problems with having `connect`'ed components nested inside a `TabPanel`. Are you sure there's no `shouldComponentUpdate` in your own code somewhere that's blocking the nested components from updating? Otherwise, if you could provide a more comprehensive example, that would help us help you figure out the problem :).

**Comment by alexanderwallin** [comment]
@upq Did you resolve your problem? If you did, could you please close this issue and, if you want, share your solution?
