### ISSUE TITLE
Ajax in tabs content

### ISSUE THREAD

**Issue by Piero87** [reactjs/react-tabs#157]
Hi,
I want make and Ajax call to fill the content of a tab, and I wanna place the fetch call inside the componentDidMount of the content component. But every time I switch between tabs the component will unmount/mount so force me to make the Ajax call again. I have found that the `forceRenderTabPanel={true}` avoid the mount/unmount problem, but I have notice also that the hidden tabs, when shown doesn't have the right style, for example the width is not calculated correctly. How avoid this problem?

**Comment by cbll** [comment]
I have the same issue. I have an Ajax call on one of three tabs. Whenever another one is clicked, the Ajax call in the "unshown" tab will also be made. Is there any way to handle that? I have also set forceRenderTabpanel to `true`, if I don't I will get an error going back to the Ajax-calling tab, from another one.

**Comment by joepvl** [comment]
Without knowing the details of your apps, generally speaking the idiomatic solution would be to lift the state that controls the content of your tabs up one or more levels in your component tree. See the React docs on this topic: https://facebook.github.io/react/docs/lifting-state-up.html.

One less ideal solution that might require less effort would be to create an abstraction that makes your fetch calls and caches the results, and use that inside your `componentDidMount` so the request won't be unnecessarily repeated.

As as aside, @Piero87: AFAIK `react-tabs` does not control (or "calculate") the width of tab panels or their contents, so that particular problem is likely to be with another part of your code.
