### ISSUE TITLE
ScrollTop after paginating

### ISSUE THREAD

**Issue by lightninglu10** [reactjs/react-tabs#230]
Hey guys, I have an app that's using react-tabs. So the situation is a bit complicated, but I sometimes use 1 tab or 2 tabs, and I have pagination going on.

Best thing to do is look at my app: https://app.codepressapp.com

So if you go to module 2 and then scroll all the way down on the info section, click exercise and scroll all the way down, THEN click back, the info section is completely scrolled down.

I tried to grab the tab and set scrollTop = 0 by

    var infoTabs = window.document.getElementsByClassName('react-tabs__tab-panel')
      
      for (var i = 0; i < infoTabs.length; i++) {
        infoTabs[i].scrollTop = 0
      }

but that's not working. It seems like it un-renders the first info tab and then when it renders back in on the back button, it will keep the old scroll position. Anyway to fix this?

**Comment by lightninglu10** [comment]
Okay I fixed this by on re-render in componentDidUpdate calling the scrollTop = 0. So this issue is sorta fixed, but shouldn't react-tabs handle pagination a different way?

**Comment by joepvl** [comment]
As far as I can tell, this is simply a side effect of React reusing the DOM node. It's leaving the node in place, only touching its content, so the scroll position is managed by the browser, which keeps it intact.

IMO your imperative fix is the right thing to do here, since there is no way to do this declaratively (react-router has [a whole documentation page](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/scroll-restoration.md) devoted to what is essentially the same problem — not that you can apply that solution in this case, though). At the moment I don't think it's react-tabs's responsibility to deal with pagination (not sure if in this case by "pagination" you mean "scroll behaviour" or navigating between the modules in your app, causing the content of the tabs to change without destroying the DOM nodes, or maybe both). However, IIRC this _has_ come up before, so I'm open to suggestions if people disagree.

I will say that we should probably add a `domRef` prop on the other components besides `Tabs` so that you can actually get to the DOM nodes through the API rather than having to use `document.querySelector` to do this kind of thing!
