### ISSUE TITLE
When clicking a tab, how can I add a callback function? 

### ISSUE THREAD

**Issue by harlemfitzgerald** [reactjs/react-tabs#249]
In this [example](https://codesandbox.io/s/x7vp30q474) that you created, if clicking on the `Preview` tab, I'd like to save the changes to `localStorage` as I do (now) do when clicking on the `finish` button. How would I go about doing so?

**Comment by joepvl** [comment]
There is no option for adding a callback that is called after a tab switch has taken place (a feature like that was requested by someone else recently, but only for use with uncontrolled mode). However, since you're using controlled mode, you can use the function you pass to the `onSelect` prop on `<Tabs>` to do the same thing. In the example's case, that's `handleSelect`.

I'm assuming that right now you have the saving logic sitting in your equivalent of the `handleButtonClick` method from the example. To prevent duplicating that logic, I would extract it out to a separate function and call it from both locations. `handleSelect` gets called with the index of the clicked tab for every tab click, so use that index to find out if you need to call the saving logic. 

Something like the following:

```jsx
class App extends React.Component {

  // ...

  previewIndex = 0;

  saveFormData = () => {
    // get data from the form and save it, like you're already doing
  }
  
  handleSelect = index => {
    if (index === this.previewIndex) {
      this.saveFormData();
    }
  }

  handlePreviewButtonClick = () => {
    this.saveFormData();
    this.setState({ selectedIndex: this.previewIndex });
  }

  // ...

}
```

Then, if you ever decided to move the Preview tab to a different position inside `<TabList>`, you'd change `previewIndex` to the corresponding integer in order to keep everything working.

**Comment by harlemfitzgerald** [comment]
Makes perfect sense! (The only thing more fab than this library is your response time! Thanks!)
