### ISSUE TITLE
Showing tab using GET request value does not work

### ISSUE THREAD

**Issue by pramodya1994** [reactjs/react-tabs#254]
Cannot expand the tab when I tried to show tab using GET request value.
here if GET result value is 1, then tab and tab panel should be shown.
but here I cannot expand tab panel by clicking on tab C.

`<TabList>
                        <Tab>A</Tab>
                        <Tab>B</Tab>
                        <Request    url={URL_FETCH_ADMIN_ROLE}
                                    method='get'
                                    accept='json'>
                            {
                                ({error, result, loading}) => {
                                    if(loading){
                                        return <Tab></Tab>;
                                    }else {
                                        if(result.body === 1){
                                              return <Tab>C</Tab>;
                                        }
                                    }
                                }
                            }
                        </Request>
</TabList>`

**Comment by pramodya1994** [comment]
<TabList>
                        <Tab>Patch and Update Sign</Tab>
                        <Tab>Patch and Update Revert</Tab>
                        <Request    url={URL_FETCH_ADMIN_ROLE}
                                    method='get'
                                    accept='json'>
                            {
                                ({error, result, loading}) => {
                                    if(loading){
                                        return <Tab></Tab>;
                                    }else {
                                        // if(result.body === 1){
                                        return <Tab>Add New Product</Tab>;
                                        // }
                                    }
                                }
                            }

**Comment by joepvl** [comment]
Unfortunately, wrapping a `<Tab/>` like this is not supported. `Tabs` expects to find an equal amount of `<Tab/>`s and `<TabPanel/>`s when it renders. In this case it will see two tabs, and then a `<Request/>` component with a function as a child.

One way to solve this particular case would be to render the entire `<Tabs/>` component after you find out the result of the request. You could still use the `<Request/>` component if you wanted to; you'd just wrap it around all of `<Tabs/>` instead of just the single `<Tab/>`.

**Comment by pramodya1994** [comment]
Thank you @joepvl
