### ISSUE TITLE
Cannot make dynamic tabs/panels from a list

### ISSUE THREAD

**Issue by jeremytowne** [reactjs/react-tabs#318]
I'm having an issue trying to dynamically construct Tabs. Ex:
```
const data = [1, 2];
...
    <div>
      <Tabs>
        <TabList>
          {data.forEach(datum => (
            <Tab>{datum}</Tab>
          ))}
        </TabList>
        {data.forEach(datum => (
          <TabPanel>{datum}</TabPanel>
        ))}
      </Tabs>
      <Tabs>
        <TabList>
          <Tab>3</Tab>
          <Tab>4</Tab>
        </TabList>
        <TabPanel>3</TabPanel>
        <TabPanel>4</TabPanel>
      </Tabs>
    </div>
```
Tabs 3 and 4 work fine, but I cannot get the ones generated from the list to work. Any suggestions on how I can accomplish this? I made a codesandbox for this: https://codesandbox.io/s/react-example-8ux6n?fontsize=14&hidenavigation=1&theme=dark

**Comment by joepvl** [comment]
Use `.map` instead of `.forEach`. If you want to know why iterating over your items with `.forEach` doesn't give you the result you want, I suggest you read through the [React docs](https://reactjs.org/docs). The page on lists may be particularly relevant for you: https://reactjs.org/docs/lists-and-keys.html.

**Comment by jeremytowne** [comment]
omg I was having a big brain fart yesterday, this is basic JS 😝. Thank you!
