### ISSUE TITLE
indexTab does't ovride

### ISSUE THREAD

**Issue by rodrigofbm** [reactjs/react-tabs#328]
```
<Tabs
            onSelect={(tabIndex) => {
              console.log(tabIndex);
              setSelectedIndex(tabIndex);
            }}
          >
            <TabList>
              <Tab tabIndex="10">
                <CustomTab isSearch>
                  <FontAwesomeIcon icon={faSearch} />
                </CustomTab>
              </Tab>
           <TabList>

           <TabPanel> Hi</TabPanel>
</Tabs>
```

onSelect prints 0 even if Tab tabIndex="10"

**Comment by joepvl** [comment]
What kind of behaviour did you expect here?

I'm guessing you meant to either fix the selected tab to the 11th one (which is at index 10), or set the tab that is selected when the component is mounted (I'll assume the code you posted is just an example, as it only has one tab, so setting the index to 10 makes no sense). You can use the [`selectedIndex`](https://github.com/reactjs/react-tabs#defaultindex-number) or [`defaultIndex`](https://github.com/reactjs/react-tabs#selectedindex-number) props for that (see [the docs](https://github.com/reactjs/react-tabs#controlled-vs-uncontrolled-mode) for more detail). The `tabIndex` prop is for controlling navigation using the tab key on the keyboard. I can see how the naming is confusing, but [`tabindex` is an html attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex), which is why we support it.

**Comment by rodrigofbm** [comment]
I want to use custom index in the Tab and when I selected this tab, the onSelected method bring me this custom index value so I can switch between the tabs with custom index
