### ISSUE TITLE
Demo source link 404s on your example

### ISSUE THREAD

**Issue by krisfields** [reactjs/react-tabs#55]

**Comment by muescha** [comment]
where:
http://rackt.org/react-tabs/example/

Link text:
Demo Source

broken link to:
https://github.com/rackt/react-tabs/blob/master/example/main.js

**Comment by danez** [comment]
@mzabriskie Could you please check why the gh-page is not updated? Maybe it was deactivated when moved? Or does there need to be a command called to update the site?

Because the link was already fixed in the gh-page branch, but the site does not refelect this change.

https://reactcommunity.org/react-tabs/example/

**Comment by danez** [comment]
@spicyj @mjackson @vjeux  Sorry for pinging you, but I would really appreciate if anyone of you could look into why the github-page of react-tabs is not updating (https://reactcommunity.org/react-tabs/example/). I wasn't able to reach @mzabriskie and I only have write access to this repo, so I can't see if the github pages are turned off. At least this would be my first guess right now, as the site is still there but not updating. Thanks

**Comment by spicyj** [comment]
![image](https://cloud.githubusercontent.com/assets/6820/18489566/db28f79a-79b2-11e6-91f0-4edbacc08e24.png)

**Comment by danez** [comment]
Hmm, thanks.
