### ISSUE TITLE
React v15

### ISSUE THREAD

**Issue by zebapy** [reactjs/react-tabs#90]
Any plans for react 15 support? I tried forking and getting started to upgrade but `npm start` has some other errors..

**Comment by chungchiehlun** [comment]
I also confronted the question.
The peerDependencies caused the error. 
Removed the peerDependencies in the package.json like below.
https://github.com/reactjs/react-tabs/blob/master/package.json#L27

**Comment by zebapy** [comment]
Is this going to move then? The project seems dead. @mzabriskie ?

**Comment by michaelzoidl** [comment]
+1

**Comment by michaelzoidl** [comment]
Ok, the work-around from @chungchiehlun seems to work, but thats just a temporary solution that doesn't block the dev-process, when do you plan to fix this?

**Comment by michaelzoidl** [comment]
Ok guys, i made a fork and updated the configs, checkout the fork [entwicklerstube/react-tabs](https://github.com/entwicklerstube/react-tabs).
Since this is just a temporary solution i suggest you can use this for now, but when the official repo fix this issue you should switch back.

Its just a fork, so just uninstall `npm uninstall react-tabs` and install the fork `npm install entwicklerstube/react-tabs` should be enough - the module works exactly like the official one.

**Comment by kachkaev** [comment]
@mzabriskie looks like we do need your help! :–) Could you please pull @michaelzoidl's commits from his fork? This should take just a couple of minutes but will save a lot of people from these nasty npm errors that we all see.

**Comment by zebapy** [comment]
@timdorr would you know who could get this moving?

**Comment by timdorr** [comment]
@mzabriskie can, but imagine he's heads down on React Rally at the moment. This can provably be picked up once that's over.

**Comment by zebapy** [comment]
@timdorr @mzabriskie is this going to be merged now?

**Comment by bjbrewster** [comment]
Sorry to bother but has this been pushed to NPM?
